# Generated by Django 4.1 on 2022-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_Name', models.CharField(blank=True, max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('int_ID', models.CharField(blank=True, max_length=15)),
                ('IP', models.CharField(blank=True, max_length=35)),
                ('Profile', models.CharField(blank=True, max_length=25)),
                ('Int_type', models.CharField(blank=True, choices=[('ISIS', 'UpLink'), ('IPOSS', 'Uplink'), ('ShutDown', 'Shut')], max_length=12)),
            ],
        ),
    ]
