# Generated by Django 4.1 on 2022-08-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='Router_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='interface',
            name='Description',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='interface',
            name='Int_type',
            field=models.CharField(blank=True, choices=[('ISIS', 'UpLink'), ('IPOSS', 'Uplink'), ('ShutDown', 'Shut'), ('LoopBack', 'loopback'), ('Vlan', 'vlan'), ('NULL', 'null'), ('vty', 'vty'), ('VlanIF', 'IF')], max_length=12),
        ),
        migrations.AlterField(
            model_name='interface',
            name='int_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
